version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home
    container_name: jenkins

  sonarqube:
    image: sonarqube:latest
    ports:
      - 9000:9000
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    container_name: sonarqube

volumes:
  jenkins_home: