sonar.projectKey=outdoor-events
sonar.projectName=Outdoor Events
sonar.projectVersion=1.0
sonar.sources=.

sonar.host.url=http://localhost:9000


# Escludi librerie e build output
sonar.exclusions=node_modules/**,dist/**,build/**
# Linguaggi supportati
sonar.language=js
sonar.sourceEncoding=UTF-8