sonar.projectKey=outdoorEventKey
sonar.projectName=OUTDOOREVENTS
sonar.projectVersion=1.0
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
sonar.login=squ_9466916c7656c6f48e719c3d0ebacc7f5ea329ee