sonar.projectKey=outdoor-events
sonar.projectName=Outdoor Events
sonar.projectVersion=1.0
sonar.sources=.

sonar.host.url=http://localhost:9000
sonar.login=sqa_0cba1f3afda595ee0cca133ed91d9df04aa4d28a

# Escludi librerie e build output
sonar.exclusions=node_modules/**,dist/**,build/**
# Linguaggi supportati
sonar.language=js
sonar.sourceEncoding=UTF-8