name: SonarCloud

on: workflow_dispatch

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1
        with:
          args: >
            -Dsonar.projectKey=outdoor-events
            -Dsonar.organization=marco-lou
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}